# Generated by Django 5.0.4 on 2024-05-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0003_coupon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('paid', '-updated')},
        ),
    ]
