# Generated by Django 5.0.4 on 2024-05-08 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('phone_number', models.CharField(max_length=11)),
                ('reservation_date', models.DateTimeField(blank=True, null=True)),
                ('admin_appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_appointments', to='reserve.appointment')),
                ('type_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_service', to='reserve.typeservice')),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='type_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_service', to='reserve.typeservice'),
        ),
    ]
