# Generated by Django 5.0.4 on 2024-04-22 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='product',
            new_name='education',
        ),
    ]
